insert into kttb_work_month(
 STAFF_ID
,WORK_DATE
,WORK_WEEK
,CORRECTION_ID
,JOB_FROM_TIME
,JOB_TO_TIME
,CORRECTION_US_TIME
,CORRECTION_MID_TIME
,INDIRECT_TIME
,TOTAL_WORK_TIME
,TOTAL_DIRECT_WORK_TIME
,OVERTIME
,ABSTRACT_ID
,PROJECT_CD
,REMARKS
,CREATESTAFF
,CREATEDAY
) values(?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,'administrator',NOW());
