name: "📊 機能開発進捗"
description: "機能ごとの製造タスクと進捗を管理するテンプレート"
title: "[Feature Progress]: "
labels: ["progress", "task"]

body:
  - type: input
    id: feature_name
    attributes:
      label: 機能名
      description: 開発対象の機能名を書いてください
      placeholder: 例: ユーザー認証（ログイン機能）
    validations:
      required: true

  - type: textarea
    id: feature_desc
    attributes:
      label: 機能の概要
      description: この機能の概要や目的を簡単に書いてください
      placeholder: 例: ユーザーがメールアドレスとパスワードでログインできる
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: 現
