name: "機能開発進捗"
description: "機能ごとの製造タスクと進捗を管理するテンプレート"
title: "[Feature Progress]: "

body:
  - type: input
    id: feature_name
    attributes:
      label: 機能名
      description: 開発対象の機能名を書いてください
      placeholder: 例: ユーザー認証（ログイン機能）
    validations:
      required: true

  - type: textarea
    id: feature_desc
    attributes:
      label: 機能の概要
      description: この機能の概要や目的を簡単に書いてください
      placeholder: 例: ユーザーがメールアドレスとパスワードでログインできる
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: 現在の進捗ステータス
      options:
        - 未着手
        - 作業中
        - レビュー待ち
        - 完了
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: サブタスク
      description: 細かい作業をタスクリスト形式で書いてください
      placeholder: |
        - [ ] DB スキーマ設計
        - [ ] API 実装
        - [ ] テストコード作成

  - type: textarea
    id: notes
    attributes:
      label: メモ・補足情報
      description: 留意点や参考資料、関連する Issue/PR を書いてください
