CREATE TABLE CLASS_MASTER (
    ID VARCHAR(40) PRIMARY KEY NOT NULL COMMENT '役職区分',
    NAME VARCHAR(40) COMMENT '役職名称'
) COMMENT '役職マスタ';

CREATE TABLE STAFF_TABLE (
    ID INT PRIMARY KEY NOT NULL COMMENT '社員ID',
    NAME VARCHAR(40) COMMENT '社員名',
    NAMEKANA VARCHAR(40) COMMENT '社員名カナ',
    ENTRY_YEAR INT COMMENT '入社年',
    GENDER VARCHAR(10) COMMENT '性別',
    CLASS_ID VARCHAR(40) COMMENT '役職区分',
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS_MASTER(ID) ON UPDATE CASCADE
) COMMENT '社員テーブル';

CREATE TABLE LOGIN_TABLE (
    -- STAFF_LOGIN.STAFF_ID -> USERS.USERNAME
    USERNAME INT(4) PRIMARY KEY NOT NULL COMMENT '社員ID',
    PASSWORD VARCHAR(500) COMMENT 'パスワード',
    -- 追加
    ENABLED BOOLEAN COMMENT '有効フラグ',
    EXPIRATION_DATE DATE COMMENT '有効期限',
    FOREIGN KEY (USERNAME) REFERENCES STAFF_TABLE(ID) ON UPDATE CASCADE
) COMMENT '社員ログインテーブル';

CREATE TABLE CORRECTION_MASTER (
    -- CORRECTION_MASTER.CORRECTION_CD -> CORRECTION_MASTER.ID
    ID INT(4) PRIMARY KEY NOT NULL COMMENT 'ID',
    STAFF_ID INT(4) NOT NULL COMMENT '社員ID',
    -- CORRECTION_MASTER.CORRECTION_US -> CORRECTION_MASTER.CORRECTION_US_TIME
    CORRECTION_US_TIME INT(4) COMMENT '稼働時間補正（通常）',
    -- CORRECTION_MASTER.CORRECTION_MID -> CORRECTION_MASTER.CORRECTION_MID_TIME
    CORRECTION_MID_TIME INT(4) COMMENT '稼働時間補正（深夜）',
    -- CORRECTION_MASTER.ABSTRACT_NAME -> CORRECTION_MASTER.ABSTRACT_ID
    ABSTRACT_ID INT(4) COMMENT '摘要区分',
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF_TABLE(ID) ON UPDATE CASCADE,
    FOREIGN KEY (ABSTRACT_ID) REFERENCES ABSTRACT_MASTER(ID) ON UPDATE CASCADE
) COMMENT '稼働補正テンプレートマスタ';

drop table WORK_MONTH_TABLE;
-- WORK_MONTH -> WORK_MONTH_TABLE
CREATE TABLE WORK_MONTH_TABLE (
    STAFF_ID INT(4) NOT NULL COMMENT '社員ID',
    -- WORK_MONTH.YEAR, WORK_MONTH.MONTH, WORK_MONTH.DAY -> WORK_MONTH.WORK_DATE
    WORK_DATE DATE COMMENT '日付',
    WORK_WEEK VARCHAR(100) COMMENT '曜日',
    -- WORK_MONTH.CORRECTION_CD -> WORK_MONTH.CORRECTION_ID
    CORRECTION_ID INT(4) COMMENT '稼働補正テンプレートCD',
    JOB_FROM_TIME DATETIME COMMENT '勤怠FROM時間',
    JOB_TO_TIME DATETIME COMMENT '勤怠TO時間',
    -- WORK_MONTH.CORRECTION_US -> WORK_MONTH.CORRECTION_US_TIME
    CORRECTION_US_TIME INT(4) COMMENT '稼働時間補正（通常）',
    -- WORK_MONTH.CORRECTION_MID -> WORK_MONTH.CORRECTION_MID_TIME
    CORRECTION_MID_TIME INT(4) COMMENT '稼働時間補正（深夜）',
    INDIRECT_TIME INT(4) COMMENT '間接時間',
    TOTAL_WORK_TIME INT(4) COMMENT '総稼働時間',
    -- WORK_MONTH.TOTAL_WORK_TIME -> WORK_MONTH.TOTAL_DIRECT_WORK_TIME
    TOTAL_DIRECT_WORK_TIME INT(4) COMMENT '総稼働時間（直接）',
    OVERTIME INT(4) COMMENT '残業時間',
    -- WORK_MONTH.ABSTRACT_NAME -> WORK_MONTH.ABSTRACT_ID
    ABSTRACT_ID INT(4) COMMENT '摘要区分',
    REMARKS VARCHAR(200) COMMENT '備考',
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF_TABLE(ID) ON UPDATE CASCADE,
--     FOREIGN KEY (CORRECTION_ID) REFERENCES CORRECTION_MASTER(ID) ON UPDATE CASCADE,
--     FOREIGN KEY (ABSTRACT_ID) REFERENCES ABSTRACT_MASTER(ID) ON UPDATE CASCADE
PRIMARY KEY (STAFF_ID, WORK_DATE)
) COMMENT '勤怠月テーブル';