CREATE TABLE CLASS_MASTER (
    ID VARCHAR(40) PRIMARY KEY NOT NULL COMMENT '役職区分',
    NAME VARCHAR(40) COMMENT '役職名称'
) COMMENT '役職マスタ';

CREATE TABLE STAFF_TABLE (
    ID INT PRIMARY KEY NOT NULL COMMENT '社員ID',
    NAME VARCHAR(40) COMMENT '社員名',
    NAMEKANA VARCHAR(40) COMMENT '社員名カナ',
    ENTRY_YEAR INT COMMENT '入社年',
    GENDER VARCHAR(10) COMMENT '性別',
    CLASS_ID VARCHAR(40) COMMENT '役職区分',
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS_MASTER(ID) ON UPDATE CASCADE
) COMMENT '社員テーブル';
